#!/usr/bin/env python
# -*- coding: UTF-8 -*-

d_month_words_kb = {
    'january': ['mth', 1],
    'jan': ['mth', 1],
    'february': ['mth', 2],
    'feb': ['mth', 2],
    'march': ['mth', 3],
    'mar': ['mth', 3],
    'april': ['mth', 4],
    'apr': ['mth', 4],
    'apl': ['mth', 4],
    'may': ['mth', 5],
    'june': ['mth', 6],
    'jun': ['mth', 6],
    'july': ['mth', 7],
    'jul': ['mth', 7],
    'august': ['mth', 8],
    'aug': ['mth', 8],
    'september': ['mth', 9],
    'sept': ['mth', 9],
    'sep': ['mth', 9],
    'october': ['mth', 10],
    'oct': ['mth', 10],
    'november': ['mth', 11],
    'nov': ['mth', 11],
    'december': ['mth', 12],
    'dec': ['mth', 12],
}
