#!/usr/bin/env python
# -*- coding: UTF-8 -*-

d_time_words_kb = {
    'second': ['time', 'sec'],
    'seconds': ['time', 'sec'],
    'sec': ['time', 'sec'],
    'secs': ['time', 'sec'],
    'minute': ['time', 'min'],
    'minutes': ['time', 'min'],
    'min': ['time', 'min'],
    'mins': ['time', 'min'],
    'hour': ['time', 'hr'],
    'hours': ['time', 'hr'],
    'hr': ['time', 'hr'],
    'hrs': ['time', 'hr'],
    'day': ['time', 'day'],
    'days': ['time', 'day'],
    'week': ['time', 'wk'],
    'weeks': ['time', 'wk'],
    'wk': ['time', 'wk'],
    'month': ['time', 'mth'],
    'months': ['time', 'mth'],
    'mth': ['time', 'mth'],
    'mths': ['time', 'mth'],
    'year': ['time', 'yr'],
    'yr': ['time', 'yr'],
    'years': ['time', 'yr'],
    'yrs': ['time', 'yr'],
    'morning': ['time', 'am'],
    'afternoon': ['time', 'pm'],
    'evening': ['time', 'pm'],
    'night': ['time', 'pm'],
    'am': ['time', 'am'],
    'pm': ['time', 'pm'],
}
